language: python
dist: xenial
sudo: true
python:
  - '3.6'
  - '3.7.0'
  - '3.7.1'
  - '3.7.2'
  - '3.7.3'
  - '3.8-dev'
install:
  - pipenv install --dev
script:
  - python -m pytest
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PW
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true